In [13]:
import pandas as pd
import numpy as np
url = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables = pd.read_html(url)

print(f"Total tables found: {len(tables)}\n")

for i, table in enumerate(tables):
    print(f"Table {i} shape: {table.shape}")
    print(table.head(), "\n")

Total tables found: 8

Table 0 shape: (3, 3)
      0     1     2
0   Aug   SEP   Oct
1   NaN    02   NaN
2  2022  2023  2024

Table 1 shape: (1, 1)
                                                   0
0  Largest economies in the world by GDP (nominal...

Table 2 shape: (1, 3)
                                                   0  \
0  > $20 trillion $10–20 trillion $5–10 trillion ...

                                                   1  \
0  $750 billion – $1 trillion $500–750 billion $2...

                                                   2
0  $50–100 billion $25–50 billion $5–25 billion <...

Table 3 shape: (214, 8)
  Country/Territory UN region IMF[1][13]            World Bank[14]             \
  Country/Territory UN region   Estimate       Year       Estimate       Year
0             World         —  105568776       2023      100562011       2022
1     United States  Americas   26854599       2023       25462700       2022
2             China      Asia   19373586  [n 1]2023       17963171  [n 3]2022
3             Japan      Asia    4409738       2023        4231141       2022
4           Germany    Europe    4308854       2023        4072192       2022

  United Nations[15]
            Estimate       Year
0           96698005       2021
1           23315081       2021
2           17734131  [n 1]2021
3            4940878       2021
4            4259935       2021

Table 4 shape: (9, 2)
  vteLists of countries by financial rankings  \
0                                       Trade
1                                  Investment
2                                       Funds
3                             Budget and debt
4                            Income and taxes

       vteLists of countries by financial rankings.1
0  Account balance % of GDP Exports by product me...
1                   FDI received past FDI abroad GFI
2  Forex reserves Forex reserves (ex. gold) Gold ...
3  Government budget PPP % of GDP per capita Cred...
4  Tax rates Inheritance tax Tax revenue Wage ave...

Table 5 shape: (7, 2)
  vteLists of countries by GDP rankings  \
0                               Nominal
1         Purchasing power parity (PPP)
2                           Growth rate
3           Gross national income (GNI)
4                   Countries by region

             vteLists of countries by GDP rankings.1
0  Per capita Past and projected per capita Secto...
1  Per capita Past per capita Past and projected ...
2  African countries Asian states European Union ...
3                  PPP per capita Nominal per capita
4  Africa PPP nominal Commonwealth of Nations PPP...

Table 6 shape: (13, 2)
             vteEconomic classification of countries  \
0  Developed country Developing country Least dev...
1                                  Three-World Model
2                       Gross domestic product (GDP)
3                                            Nominal
4                      Purchasing power parity (PPP)

           vteEconomic classification of countries.1
0  Developed country Developing country Least dev...
1  First World Second World Third World Fourth World
2  Nominal By country past and projected per capi...
3  By country past and projected per capita per c...
4  By country future estimates per capita per cap...

Table 7 shape: (2, 2)
                               0  \
0                        Nominal
1  Purchasing power parity (PPP)

                                                   1
0  By country past and projected per capita per c...
1  By country future estimates per capita per cap...

In [14]:
df = tables[3]
df.columns = range(df.shape[1]) #replaces column header with numbers
df = df[[0,2]]    #now our dataframe has only country name and estimated gdp by IMF
df = df.iloc[1:11,:]    #1:11 means row 1-10 and : means all columns
df.columns = ['Country','GDP (Million USD)']
print(df)

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [15]:
df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)
df["GDP (Million USD)"] = df["GDP (Million USD)"]/1000
df["GDP (Million USD)"] = np.round(df["GDP (Million USD)"],2)
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [ ]:
df.to_csv("GDP_extraction.csv")
with open("GDP_extraction.csv", "r") as file:
    print(file.read())

<_io.TextIOWrapper name='GDP_extraction.csv' mode='r' encoding='cp1252'>